var appConstants = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    LOGIN_EVENT: "LOGIN_EVENT",
    ACCT_CREATE_EVENT: "ACCT_CREATE_EVENT",

    FLICKR_URL: "FLICKR_URL",
    FLICKR_URL_ERR: "FLICKR_URL_ERR",
    FLICKR_RESTORE_LIVE_EVENT: "FLICKR_RESTORE_LIVE_EVENT",

    FLICKR_SAVE_EVENT: "FLICKR_SAVE_EVENT",
    FLICKR_LOAD_EVENT: "FLICKR_LOAD_EVENT",

    FLICKR_SEARCH_EVENT: "FLICKR_SEARCH_EVENT",
    FLICKR_SEARCH_ERR_EVENT: "FLICKR_SEARCH_ERR_EVENT",
    FLICKR_RESTORE_SEARCH_EVENT: "FLICKR_RESTORE_SEARCH_EVENT",
    FLICKR_AUTOPLAY_STOP_EVENT: "FLICKR_AUTOPLAY_STOP_EVENT",

    KEEPALIVE_INIT_EVENT: "KEEPALIVE_INIT_EVENT",
    KEEPALIVE_EVENT: "KEEPALIVE_EVENT"
};

module.exports = appConstants;