var appConstants = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    LOGIN_EVENT: "LOGIN_EVENT",
    FLICKR_URL: "FLICKR_URL",
    FLICKR_URL_ERR: "FLICKR_URL_ERR",
    FLICKR_SAVE_EVENT: "FLICKR_SAVE_EVENT",
    FLICKR_SAVED_IMAGES_EVENT: "FLICKR_SAVED_IMAGES_EVENT",
    FLICKR_RESTORE_LIVE_EVENT: "FLICKR_RESTORE_LIVE_EVENT"
};

module.exports = appConstants;